# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tagBase: '$(Build.BuildNumber)'
  repo: djryanj.azurecr.io
  image: solar-scraper

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build Docker Images
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: enable-qemu-arm.yaml
    - bash: |
        docker buildx build -f Dockerfile --platform linux/arm64 -t $(repo)/$(image):$(tagBase)-arm64 .
        docker build -f Dockerfile -t $(repo)/$(image):$(tagBase)-amd64 .
      displayName: Build Multi-Arch Images
    - task: Docker@2
      displayName: Log in to ACR
      inputs:
        containerRegistry: djryanj-acr
        command: login
    - task: Docker@2
      displayName: Push Images
      inputs:
        containerRegistry: djryanj-acr
        repository: humidor-sensor-scraper
        command: push
        tags: |
          $(tagBase)-arm64
          $(tagBase)-amd64
    - bash: |
        docker manifest create $(repo)/$(image):$(tagBase) \
          $(repo)/$(image):$(tagBase)-arm64 \
          $(repo)/$(image):$(tagBase)-amd64
        docker manifest push $(repo)/$(image):$(tagBase)
      displayName: Create and push Manifest    
    - task: Docker@2
      displayName: Log out
      inputs:
        containerRegistry: djryanj-acr
        command: logout
        